## Quiz

Assume you define an array `a` as following:

In [33]:
a = np.arange(4)
a

array([0, 1, 2, 3])

What is the value of `a` after these operations:

In [34]:
a = np.arange(4)

b = a[::2]
b[0] = 10
print(a)

[10  1  2  3]


In [41]:
a = np.arange(4)

b = a[[0, 2]]
b[0] = 10
print(a)

[0 1 2 3]


In [44]:
a = np.arange(4)

a[[0, 1, 3]] = 10
print(a)

[10 10  2 10]


In [45]:
a = np.arange(4)

a[a>2] = 10
print (a)

[ 0  1  2 10]
