In [4]:
import xarray as xr
import numpy as np

In [5]:
data = xr.DataArray(np.random.rand(5))

In [6]:
data

<xarray.DataArray (dim_0: 5)>
array([ 0.19597555,  0.56921482,  0.22690033,  0.50702378,  0.54791444])
Coordinates:
  * dim_0    (dim_0) int64 0 1 2 3 4

## Dimension labels

In [77]:
data1 = xr.DataArray(np.random.rand(4, 2), [('sample',['a', 'b', 'c', 'd']), ('size',['width', 'height'])])

In [107]:
data1.dtype

dtype('float64')

In [78]:
data1

<xarray.DataArray (sample: 4, size: 2)>
array([[ 0.86866115,  0.40762156],
       [ 0.25137188,  0.83091033],
       [ 0.49859054,  0.57916223],
       [ 0.13570944,  0.01760468]])
Coordinates:
  * sample   (sample) |S1 'a' 'b' 'c' 'd'
  * size     (size) |S6 'width' 'height'

In [85]:
data1.sum('sample')

<xarray.DataArray (size: 2)>
array([ 1.75433301,  1.8352988 ])
Coordinates:
  * size     (size) |S6 'width' 'height'

## Indexing

In [105]:
data1[2]

<xarray.DataArray (size: 2)>
array([ 0.49859054,  0.57916223])
Coordinates:
    sample   |S1 'c'
  * size     (size) |S6 'width' 'height'

In [106]:
data1.loc['a']

<xarray.DataArray (size: 2)>
array([ 0.86866115,  0.40762156])
Coordinates:
    sample   |S1 'a'
  * size     (size) |S6 'width' 'height'

In [108]:
data1.sel(size='width')

<xarray.DataArray (sample: 4)>
array([ 0.86866115,  0.25137188,  0.49859054,  0.13570944])
Coordinates:
  * sample   (sample) |S1 'a' 'b' 'c' 'd'
    size     |S6 'width'

## Alignment

In [92]:
day2 = xr.DataArray(np.random.rand(4,2), [('sample',['b', 'c', 'd', 'e']), ('size', ['width', 'height'])])

In [93]:
data1 + day2

<xarray.DataArray (sample: 3, size: 2)>
array([[ 0.89587212,  1.03816913],
       [ 1.35330607,  1.25184663],
       [ 1.11904872,  0.61373682]])
Coordinates:
  * sample   (sample) object 'b' 'c' 'd'
  * size     (size) |S6 'width' 'height'

## Broadcasting

In [99]:
units = xr.DataArray([0.001, 0.01, 1], [('unit', ['mm', 'cm', 'm'])])

In [100]:
data1 * units

<xarray.DataArray (sample: 4, size: 2, unit: 3)>
array([[[  8.68661152e-04,   8.68661152e-03,   8.68661152e-01],
        [  4.07621555e-04,   4.07621555e-03,   4.07621555e-01]],

       [[  2.51371876e-04,   2.51371876e-03,   2.51371876e-01],
        [  8.30910332e-04,   8.30910332e-03,   8.30910332e-01]],

       [[  4.98590537e-04,   4.98590537e-03,   4.98590537e-01],
        [  5.79162233e-04,   5.79162233e-03,   5.79162233e-01]],

       [[  1.35709444e-04,   1.35709444e-03,   1.35709444e-01],
        [  1.76046833e-05,   1.76046833e-04,   1.76046833e-02]]])
Coordinates:
  * sample   (sample) |S1 'a' 'b' 'c' 'd'
  * size     (size) |S6 'width' 'height'
  * unit     (unit) |S2 'mm' 'cm' 'm'

# Exercise

These two arrays contain temperatures in Erlangen and Paris recorded every month of 2015:

```
erlangen = []
paris = []
```

Design a `DataArray` for storing these data. Calculate average temperature per location.Add measurement in third city.

In [29]:

months = range(12)
erlangen = np.random.randn(12)
paris = np.random.randn(12)

In [46]:
data = xr.DataArray([erlangen, paris], [('city', ['Erlangen', 'Paris']), ('month', months)])

In [47]:
data

<xarray.DataArray (city: 2, month: 12)>
array([[-0.57577486, -0.72116594, -0.76420096, -0.30790361,  0.12582586,
        -2.29440426, -0.46819937,  0.37937205,  0.91693077, -0.83358682,
         1.14229471,  0.2530109 ],
       [ 1.26075554, -0.89508155,  1.3983479 ,  0.58154699,  0.84078393,
         0.46338294,  0.45022708, -1.32997518, -0.85903915, -1.73596396,
        -1.33401731, -1.67657459]])
Coordinates:
  * city     (city) |S8 'Erlangen' 'Paris'
  * month    (month) int64 0 1 2 3 4 5 6 7 8 9 10 11

In [48]:
data.mean('month')

<xarray.DataArray (city: 2)>
array([-0.26231679, -0.23630061])
Coordinates:
  * city     (city) |S8 'Erlangen' 'Paris'

In [49]:
data2 = xr.DataArray([np.arange(12)], [('city', ['Amsterdam']), ('month', months)])

In [52]:
data + data2

<xarray.DataArray (city: 0, month: 12)>
array([], shape=(0, 12), dtype=float64)
Coordinates:
  * city     (city) object 
  * month    (month) int64 0 1 2 3 4 5 6 7 8 9 10 11

In [51]:
xr.concat([data, data2], 'city')

<xarray.DataArray (city: 3, month: 12)>
array([[ -0.57577486,  -0.72116594,  -0.76420096,  -0.30790361,
          0.12582586,  -2.29440426,  -0.46819937,   0.37937205,
          0.91693077,  -0.83358682,   1.14229471,   0.2530109 ],
       [  1.26075554,  -0.89508155,   1.3983479 ,   0.58154699,
          0.84078393,   0.46338294,   0.45022708,  -1.32997518,
         -0.85903915,  -1.73596396,  -1.33401731,  -1.67657459],
       [  0.        ,   1.        ,   2.        ,   3.        ,
          4.        ,   5.        ,   6.        ,   7.        ,
          8.        ,   9.        ,  10.        ,  11.        ]])
Coordinates:
  * month    (month) int64 0 1 2 3 4 5 6 7 8 9 10 11
  * city     (city) object 'Erlangen' 'Paris' 'Amsterdam'

# Other features

* `Dataset` -- key/value store; generalisation of `DataFrame` in `pandas` for N-dimenisonal data
* groupby/split/combine
* NetCDF io