# Universal functions

From NumPy [docs](http://docs.scipy.org/doc/numpy/reference/ufuncs.html):
    
    A universal function (or ufunc for short) is a function that operates on ndarrays in an element-by-element fashion, supporting array broadcasting, type casting, and several other standard features. That is, a ufunc is a “vectorized” wrapper for a function that takes a fixed number of scalar inputs and produces a fixed number of scalar outputs.

## Universal functions

In [1]:
import numpy as np
np.info(np.add)

add(x1, x2[, out])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).

Returns
-------
add : ndarray or scalar
    The sum of `x1` and `x2`, element-wise.  Returns a scalar if
    both  `x1` and `x2` are scalars.

Notes
-----
Equivalent to `x1` + `x2` in terms of array broadcasting.

Examples
--------
>>> np.add(1.0, 4.0)
5.0
>>> x1 = np.arange(9.0).reshape((3, 3))
>>> x2 = np.arange(3.0)
>>> np.add(x1, x2)
array([[  0.,   2.,   4.],
       [  3.,   5.,   7.],
       [  6.,   8.,  10.]])


### Keyword arguments:
    
* `out` -- where to store output 
* `where` -- boolean array showing for which elements of the input arrays to calculate the ufunc

In [2]:
out = np.zeros(2)
np.add([1,2], [3,4], where=[False, True], out=out)
out

array([ 0.,  6.])

### Attributes

`nin`, `nout`, `nargs`, `ntypes`, `types`, `identity`

In [3]:
np.add.nin, np.add.nout

(2, 1)

### Methods

`reduce`, `accumulate`, `reduceat`, `outer`,  `at`

In [4]:
np.add.reduce([1, 2, 3])

6

In [5]:
np.add.accumulate([1, 2, 3])

array([1, 3, 6])

In [6]:
np.add.outer([1, 2, 3], [1, 2, 3])

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [7]:
arr = np.array([1, 2, 3])
np.add.at(arr, [0, 2], 10)
arr

array([11,  2, 13])

### Quiz

What will be the content of `arr`?

```python
arr = np.array([4, 2, 3.])
arr[[0, 1, 2, 2]]+= 1
```

In [8]:
arr = np.array([4, 2, 3.])
np.add.at(arr, [0, 1, 2, 2], 1)
arr

array([ 5.,  3.,  5.])

### Exercise

Calculate the product of all elements of `a`:
```
a = np.random.randn(10)
```

### Exercise

*From NumPy 100 exercises*:

Compute `((A+B)*(-A/2))` in place (without a copy):

```
A = np.ones(3)*1
B = np.ones(3)*2
```

## Generalised ufuncs

In regular ufuncs, the elementary function is limited to element-by-element operations, whereas the generalized version (gufuncs) supports “sub-array” by “sub-array” operations. 

For example,

`np.add` (standard ufunc) has the following signature `(), () -> ()` i.e. it produces a scalar from two scalars

In [9]:
np.add(1, 2)

3

`np.linalg.det` (generalised ufunc or gufunc) has the following signature `(m,m) -> ()`, i.e. it takes a single square matrix and produces a scalar

In [10]:
np.linalg.det([[1, 2], [3, 4]])

-2.0000000000000004

If inputs have larger number of dimensions the `(g)func`s will broadcast and iterate over the remaining dimensions.

In [11]:
np.add([1, 2], [3, 4]) # (2,), (2,) -> (2,)

array([4, 6])

In [12]:
np.linalg.det(np.random.randn(3, 2, 2)) # (3, 2, 2) -> (3,)

array([-0.49742401, -1.92430929,  0.42316641])

Note that this implements linear algebra methods for stacked arrays!

## `einsum`

`np.einsum` implements sort-of gufunc functionality for operations involving only sums and products. To calculate outer product of two vectors:

In [31]:
a = np.arange(2)
b = np.arange(3)

np.einsum('i,j->ij', a, b)

array([[0, 0, 0],
       [0, 1, 2]])

To work with stacked arrays, you can put ellipsis (`...`) in place of broadcasted dimensions:

In [24]:
A = np.random.rand(5, 1, 2)
B = np.random.rand(1, 4, 3)
C = np.einsum('...i,...j->...ij', A, B)
C.shape

(5, 4, 2, 3)

### Exercise  (`np.einsum`)

*Exercise from [100 numpy exercises](https://github.com/rougier/numpy-100)*

Use `np.einsum` to calculate the **diagonal of a dot product** of two matrices (`np.diag(np.dot(A, B))`).

```
A = np.arange(6).reshape(3, 2)
B = np.ones((2, 3))
np.einsum('your signature goes here', A, B)
```

Then, test your solution on stacked arrays:

```
A = np.arange(12).reshape(2, 3, 2)
B = np.ones((2, 3))
```

## Further reading
* Ufuncs: http://docs.scipy.org/doc/numpy/reference/ufuncs.html
* Basic guide to einsum, http://ajcr.net/Basic-guide-to-einsum/