# 1. Broadcasting

## Exercise: Normalising data

Given the following array:

```
a = np.array([[2, 3, 1], [4, 1, 1]])
```

For each column of `a` subtract mean across rows. Next, from each row subtract its mean across columns.

In [17]:
import numpy as np

a = np.array([[2, 3, 1], [4, 1, 1]])
print(a-a.mean(0))


[[-1.  1.  0.]
 [ 1. -1.  0.]]


In [18]:
print(a-a.mean(1)[:, np.newaxis])

[[ 0.  1. -1.]
 [ 2. -1. -1.]]


##  Exercise: Route 66

*Adapted from [Scipy Lectures](http://www.scipy-lectures.org/intro/numpy/index.html) by Emmanuelle Gouillart, Didrik Pinte, Gaël Varoquaux, and Pauli Virtanen*

Given the mileposts construct an array of distances (in miles) between cities of Route 66: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff and Los Angeles.

```
mileposts = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])
```
![Distances on Route 66](route66.png)

In [21]:
mileposts = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])
mileposts - mileposts[:, np.newaxis]

array([[    0,   198,   303,   736,   871,  1175,  1475,  1544,  1913,
         2448],
       [ -198,     0,   105,   538,   673,   977,  1277,  1346,  1715,
         2250],
       [ -303,  -105,     0,   433,   568,   872,  1172,  1241,  1610,
         2145],
       [ -736,  -538,  -433,     0,   135,   439,   739,   808,  1177,
         1712],
       [ -871,  -673,  -568,  -135,     0,   304,   604,   673,  1042,
         1577],
       [-1175,  -977,  -872,  -439,  -304,     0,   300,   369,   738,
         1273],
       [-1475, -1277, -1172,  -739,  -604,  -300,     0,    69,   438,
          973],
       [-1544, -1346, -1241,  -808,  -673,  -369,   -69,     0,   369,
          904],
       [-1913, -1715, -1610, -1177, -1042,  -738,  -438,  -369,     0,
          535],
       [-2448, -2250, -2145, -1712, -1577, -1273,  -973,  -904,  -535,
            0]])

## Exercise: Three-dimensional broadcasting

Below, insert `np.newaxis` to produce the array containing the sum of every element in `x` with every element in `y`

```python
x = np.random.rand(3, 5)
y = np.random.randint(10, size=8)
z = x + y# FIX THIS
```

In [25]:
x = np.random.rand(3, 5)
y = np.random.randint(10, size=8)
z = x[:, :, np.newaxis] + y
z.shape

(3, 5, 8)

# 2. Memory layout

## Exercise: Broadcasting revisited

Explain how broadcasting works internally using the example below. What will be the `shape` and `strides` of `x` and `y` after broadcasting. Test it using `np.broadcast_arrays` in the following example and look at `strides` and `shape` properties of both arrays.

```python
x = np.random.rand(5, 10)
y = np.random.rand(10)
z = x + y

xb, yb = np.broadcast_arrays(x, y)
```

In [47]:
x = np.random.rand(5, 10)
y = np.random.rand(10)
z = x + y

xb, yb = np.broadcast_arrays(x, y)
print("Before broadcasting:")
print("  Shape:", y.shape, "Strides:", y.strides)
xb, yb = np.broadcast_arrays(x, y)
print("After broadcasting:")
print("  Shape:", yb.shape, "Strides:", yb.strides)

Before broadcasting:
  Shape: (10,) Strides: (8,)
After broadcasting:
  Shape: (5, 10) Strides: (0, 8)


## Exercise: Sliding window

*Modified Exercise by Stéfan van der Walt and Juan Nunez-Iglesias*

Use `as_strided` to produce a sliding-window view of a 1D array.

```python
def sliding_window(arr, size=2):
    """Produce an array of sliding window views of `arr`
    
    Parameters
    ----------
    arr : 1D array, shape (N,)
        The input array.
    size : int, optional
        The size of the sliding window.
        
    Returns
    -------
    arr_slide : 2D array, shape (N - size + 1, size)
        The sliding windows of size `size` of `arr`.
        
    Examples
    --------
    >>> a = np.array([0, 1, 2, 3])
    >>> sliding_window(a, 2)
    array([[0, 1],
           [1, 2],
           [2, 3]])
    """
    return arr  # fix this
```

In [41]:
def sliding_window(arr, size=2):
    """Produce an array of sliding window views of `arr`

    Parameters
    ----------
    arr : 1D array, shape (N,)
        The input array.
    size : int, optional
        The size of the sliding window.

    Returns
    -------
    arr_slide : 2D array, shape (N - size + 1, size)
        The sliding windows of size `size` of `arr`.

    Examples
    --------
    >>> a = np.array([0, 1, 2, 3])
    >>> sliding_window(a, 2)
    array([[0, 1],
           [1, 2],
           [2, 3]])
    """
    assert arr.ndim == 1
    N = len(arr)
    new_shape = (N - size + 1, size)
    new_strides = (arr.itemsize, arr.itemsize)
    strided_arr = np.lib.stride_tricks.as_strided(arr,
                                                  shape=new_shape,
                                                  strides=new_strides)
    return strided_arr  # fix this

a = np.array([0, 1, 2, 3])
sliding_window(a, 2)

array([[0, 1],
       [1, 2],
       [2, 3]])

## Exercise: Fastest changing index 
 
Compare the time of summing over rows and columns of an array `A = np.random.rand(3000, 3000)`. Next, try the same with array with Fortran order. How would you explain the differences? (*Hint*: To measure evaluation time you can use `%timeit` of ipython)

In [57]:
A = np.random.rand(3000, 3000)
%timeit A.sum(0)
%timeit A.sum(1)

100 loops, best of 3: 6.06 ms per loop
100 loops, best of 3: 5.04 ms per loop


In [59]:
A_fortran = np.array(A, order='F')
%timeit A_fortran.sum(0)
%timeit A_fortran.sum(1)

100 loops, best of 3: 4.71 ms per loop
100 loops, best of 3: 5.89 ms per loop


# 3. dtypes and structured array

## Exercise: Integer or real number?

Construct the array 
```python
x = np.array([0, 1, 2, 255], dtype=np.uint8)
```

Can
you explain the difference obtained by `x + 1` and `x.astype(int) + 1`?

In [69]:
x = np.array([0, 1, 2, 255], dtype=np.uint8)
print(x + 1)
print(x.astype(int) + 1)

[1 2 3 0]
[  1   2   3 256]


### Exercise: Structured data types

*This exercise was proposed by Stéfan van der Walt (https://python.g-node.org/python-summerschool-2014/_media/numpy_advanced.tar.bz2)*

Design a data-type for storing the following record:

 - Timestamp in nanoseconds (a 64-bit unsigned integer)
 - Position (x- and y-coordinates, stored as floating point numbers)

Use it to represent the following data:

```
dt = np.dtype(<your code here>)
x = np.array([(100, (0, 0.5)),
              (200, (0, 10.3)),
              (300, (5.5, 15.1))], dtype=dt)
```

Have a look at the ``np.dtype`` docstring if you need help.
After constructing ``x``, try to print all the ``x`` values for which timestamp
is greater than 100 (hint: something of the form ``y[y > 100]``).

In [76]:
dt = np.dtype([('timestamp', np.uint64), 
               ('position', [('x', np.float),
                             ('y', np.float)])])
x = np.array([(100, (0, 0.5)),
              (200, (0, 10.3)),
              (300, (5.5, 15.1))], dtype=dt)
print(x[x['timestamp'] > 100])

[(200, (0.0, 10.3)) (300, (5.5, 15.1))]


### Exercise: Structured file I/O

*Modified from exercise by Stéfan van der Walt (https://python.g-node.org/python-summerschool-2014/_media/numpy_advanced.tar.bz2)*

Given the ``data.txt`` file with the following content:

In [80]:
%%file data.txt
#rank         lemma (10 letters max)      frequency       dispersion
21             they                        1865844         0.96
42             her                         969591          0.91
49             as                          829018          0.95
7              to                          6332195         0.98
63             take                        670745          0.97
14             you                         3085642         0.92
35             go                          1151045         0.93
56             think                       772787          0.91
28             not                         1638883         0.98

Overwriting data.txt


Design a suitable structured data type, then load the data from the text
file using ``np.loadtxt``.  Here's a skeleton to start with:

```python
import numpy as np
data = np.loadtxt('data.txt', dtype=...)  # Modify this line
```

Examine the data you got:
 - Extract words only
 - Extract the 3rd row
 - Print all words with ``rank < 30``
 - Sort the data according to frequency (see np.sort).

In [89]:
data = np.loadtxt('data.txt', dtype=[('rank', np.int),
                                     ('lemma', 'S10'),
                                     ('frequency', np.int),
                                     ('dispersion', np.float)])

In [95]:
data['lemma']
data[3]
data[data['rank'] < 30]
np.sort(data, order='frequency')

array([(63, b'take', 670745, 0.97), (56, b'think', 772787, 0.91),
       (49, b'as', 829018, 0.95), (42, b'her', 969591, 0.91),
       (35, b'go', 1151045, 0.93), (28, b'not', 1638883, 0.98),
       (21, b'they', 1865844, 0.96), (14, b'you', 3085642, 0.92),
       (7, b'to', 6332195, 0.98)], 
      dtype=[('rank', '<i8'), ('lemma', 'S10'), ('frequency', '<i8'), ('dispersion', '<f8')])

# 4. `xarray`

## Exercise

These two arrays contain average monthly temperatures (in Celsius degrees) in Erlangen and Paris:

```
erlangen = [-0.5, 0.7, 4.4, 8.5, 13.3, 16.7, 18.2, 17.5, 13.7, 8.9, 4.0, 0.9]
paris = [3.3, 4.2, 7.8, 10.8, 14.3, 17.5, 19.4, 19.1, 16.4, 11.6, 7.2, 4.2]
```

Design a `DataArray` for storing these data. Calculate average annual temperature per location.

In [1]:
import xarray as xr
import numpy as np
erlangen = [-0.5, 0.7, 4.4, 8.5, 13.3, 16.7, 18.2, 17.5, 13.7, 8.9, 4.0, 0.9]
paris = [3.3, 4.2, 7.8, 10.8, 14.3, 17.5, 19.4, 19.1, 16.4, 11.6, 7.2, 4.2]

months = np.arange(12) + 1
temperature = xr.DataArray([erlangen, paris], [('city', ['erlangen', 'paris']),
                                               ('month', months)])
temperature.mean('month')

<xarray.DataArray (city: 2)>
array([  8.85833333,  11.31666667])
Coordinates:
  * city     (city) <U8 'erlangen' 'paris'

## Exercise

*Inspired by data science [challenge](http://www.ramp.studio/events/drug_spectra) by C. Marini et al*

A researcher measured a [Raman spectrum](https://en.wikipedia.org/wiki/Raman_spectroscopy) of an unknown sample. Now he wants to determine the substance and its concentration. He has calibration data with Raman spectra of four different compounds at three different concentrations. Calculate mean square error between sample and all calibration spectra and find the closest compound and concentration.

```python
import pandas as pd
df = pd.DataFrame.from_csv('raman_data.csv', index_col=[0, 1, 2])
calibration = xr.DataArray.from_series(df['Raman'])

sample = xr.DataArray([[0, 10]], [('sample', ['X1042']),
                                  ('wavelength', [100, 300])])
```

**Hint**: To find the calibration sample with minimum error, you may convert the DataArray to pandas:

```python
err.to_series().argmin()
```

In [2]:
# Code used to generate the calibration data
import xarray as xr
import numpy as np

spectra = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 1], [0, 1, 1]])
concentrations = np.array([1., 10., 100.])
data = spectra * concentrations[:, None, None]
dataarray = xr.DataArray(data, [
                               ('concentration', [1, 2, 5]),
                               ('compound', ['A', 'B', 'C', 'D']),
                               ('wavelength', [100, 200, 300])
                               ],
                              name='Raman')

dataarray.to_dataframe().to_csv('raman_data.csv')

In [3]:
# Solution 

import pandas as pd
df = pd.DataFrame.from_csv('raman_data.csv', index_col=[0, 1, 2])
calibration = xr.DataArray.from_series(df['Raman'])

sample = xr.DataArray([[0, 10]], [('sample', ['X1042']),
                                  ('wavelength', [100, 300])])

err = ((calibration - sample)**2).sum('wavelength')
err.to_series().argmin()

(2, 'C', 'X1042')

# 5. Array interface

## Exercise

Original exercise by Stefan van der Walt and Juan Nunez-Iglesias.

An author of a foreign package (included with the exercizes as
``problems/mutable_str.py``) provides a string class that
allocates its own memory:

```ipython
In [1]: from mutable_str import MutableString
In [2]: s = MutableString('abcde')
In [3]: print s
abcde
```

You'd like to view these mutable (*mutable* means the ability to modify in place)
strings as ndarrays, in order to manipulate the underlying memory.

Add an __array_interface__ dictionary attribute to s, then convert s to an
ndarray. Numerically add "2" to the array (use the in-place operator ``+=``).

Then print the original string to ensure that its value was modified.

> **Hint:** Documentation for NumPy's ``__array_interface__``
  may be found [in the online docs](http://docs.scipy.org/doc/numpy/reference/arrays.interface.html).

Here's a skeleton outline:

```python
import numpy as np
from mutable_str import MutableString

s = MutableString('abcde')

# --- EDIT THIS SECTION ---

# Create an array interface to this foreign object
s.__array_interface__ = {'data' : XXX # (ptr, is read_only?)
                         'shape' : XXX,
                         'typestr' : XXX, # typecode unsigned character
                         }

# --- EDIT THIS SECTION ---

print('String before converting to array:', s)
sa = np.asarray(s)

print('String after converting to array:', sa)

sa += 2
print('String after adding "2" to array:', s)
```

In [4]:
import numpy as np
from mutable_str import MutableString

s = MutableString('abcde')

# --- EDIT THIS SECTION ---

# Create an array interface to this foreign object
s.__array_interface__ = {'data' : (s.data_ptr, False), # (ptr, is read_only?)
                         'shape' : (len(s),),
                         'typestr' : '|u1', # typecode unsigned character
                         }

# --- EDIT THIS SECTION ---

print('String before converting to array:', s)
sa = np.asarray(s)

print('String after converting to array:', sa)

sa += 2
print('String after adding "2" to array:', s)

String before converting to array: abcde
String after converting to array: [ 97  98  99 100 101]
String after adding "2" to array: cdefg


# 6. Ufuncs

### Exercise

*Exercise from [NumPy 100 exercises](https://github.com/rougier/numpy-100/blob/master/100%20Numpy%20exercises.md)*:

Compute `((A+B)*(-A/2))` in place (without a copy):

```
A = np.ones(3)*1
B = np.ones(3)*2
```

**Hint**: Use `out` argument of ufuncs.

In [5]:
A = np.ones(3)*1
B = np.ones(3)*2

np.add(A, B, out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

### Exercise  (`np.einsum`)

*Exercise from [100 numpy exercises](https://github.com/rougier/numpy-100)*

Use `np.einsum` to calculate the **diagonal of a dot product** of two matrices (`np.diag(np.dot(A, B))`).

```
A = np.arange(6).reshape(3, 2)
B = np.ones((2, 3))
np.einsum('your signature goes here', A, B)
```

Then, test your solution on stacked arrays:

```
A = np.arange(12).reshape(2, 3, 2)
B = np.ones((2, 3))
```

In [6]:
A = np.arange(12).reshape(2, 3, 2)
B = np.ones((2, 3))
np.einsum('...ij,...ji->...i', A, B)

array([[  1.,   5.,   9.],
       [ 13.,  17.,  21.]])


# 7. Extending NumPy

### Exercise

Take the following function calculating logit and turn it into a ufunc using the above example.

```cython

cdef extern from "math.h":
    double log "log" (double) nogil
    
import cython

@cython.cdivision(True)
cdef double logit_double(double p) nogil:
    p = p/(1-p);
    p = log(p);
    return p
```

In [7]:
%load_ext cython

In [8]:
%%cython

# The elementwise function

cdef extern from "math.h":
    double log "log" (double) nogil
    
import cython

@cython.cdivision(True)
cdef double logit_double(double p) nogil:
    p = p/(1-p);
    p = log(p);
    return p


# Required module initialization
# ------------------------------

cimport numpy as np
np.import_array()
np.import_ufunc()

# The actual ufunc declaration
# ----------------------------

cdef np.PyUFuncGenericFunction loop_func[1]
cdef char input_output_types[2]
cdef void *elementwise_funcs[1]

loop_func[0] = np.PyUFunc_d_d # generic function to implement looping

input_output_types[0] = np.NPY_DOUBLE
input_output_types[1] = np.NPY_DOUBLE


elementwise_funcs[0] = <void*>logit_double

logit = np.PyUFunc_FromFuncAndData(
    loop_func,
    elementwise_funcs,
    input_output_types,
    1, # number of supported input types
    1, # number of input args
    1, # number of output args
    0, # `identity` element, never mind this
    "logit", # function name
    "computes logit", # docstring
    0 # unused
    )


In [9]:
import numpy as np
a = np.array([0.9, 0.3], dtype=np.double)
logit(a)

array([ 2.19722458, -0.84729786])